version: '3'
services:
  postgres:
    container_name: timeline-pg
    image: postgres:latest
    hostname: localhost
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: timeline_db
    expose:
      - "5432" # Expose PostgreSQL port for other containers
    volumes:
      - pg-data:/var/lib/postgresql/data
  # pgadmin:
  #   container_name: timeline-pgadmin
  #   image: dpage/pgadmin4
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  node-app:
    container_name: timeline-express
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
  # angular-app:
  #   container_name: timeline-angular
  #   build:
  #     context: .
  #   ports:
  #     - "4200:4200"
volumes:
  pg-data:
